---
vagrantfile-local:
    vm:
        box: ubuntu14.04LTS_cibox.box
        box_url: 'http://128.199.55.125/ubuntu14.04LTS_cibox.box'
        hostname: d8pp.dev
        network:
            private_network: 192.168.93.187
            forwarded_port:
                CocLsFE7aIwA:
                    host: '8081'
                    guest: '80'
                CocLsFE7aIwE:
                    host: '8083'
                    guest: '3306'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '1024'
                    name: 'd8pp'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            lxc:
                box: fgrehm/trusty64-lxc
                box_url: https://vagrantcloud.com/fgrehm/boxes/trusty64-lxc/versions/1.2.0/providers/lxc.box
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            - id: drupal
              source: ./
              target: /var/www
              nfs: 'true'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
        - htop
        - git
        - php5-memcached
        - memcached
        - unzip
        - libaugeas-dev
        - libaugeas-ruby
        - imagemagick
        - php5-imagick
    dot_files:
        - bash_aliases: null
    _prevent_empty: ''
