name: 'Intranet config storage'
description: 'Config storage module that contains sidewide configurations.'
package: Intranet
type: module
version: 1.0
core: 8.x

dependecies:
  - intranet_helper
  - path
