---
# This playbook installs apache

- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  sudo: yes

  vars:
    apache_listen_port: 80
    apache_listen_port_ssl: 443
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_vhosts:
      - {
        servername: "d8pp.dev",
        documentroot: "/var/www/drupal"
      }
      - { servername: "client.d8pp.dev", documentroot: /var/www/angular/app" }
#    apache_vhosts_ssl:
#      - {
#        servername: "dmjx.192.168.51.121.xip.io",
#        documentroot: "/var/www/drupal",
#        certificate_file: "/var/www/ssl_certificate/example.crt",
#        certificate_key_file: "/var/www/ssl_certificate/example.key",
#      }
    apache_mods_enabled:
      - rewrite.load
      - headers.load
      - ssl.load

  roles:
    - { role: ansible-role-apache }
